name: build-test
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        # At the time of writing macos-latest is mac 10; we need 11 to build a universal binary.
        os: [ubuntu-latest, macos-11, windows-2019]
        node: [12, 14, 16]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} / Node ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          architecture: x64
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
